#
# This workflow calls the main distribution pipeline from DuckDB to build, test and (optionally) release the extension
#
name: Main Extension Distribution Pipeline
on:
  push:
  pull_request:
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}-${{ github.head_ref || '' }}-${{ github.base_ref || '' }}-${{ github.ref != 'refs/heads/main' || github.sha }}
  cancel-in-progress: true

jobs:
  duckdb-next-build:
    name: Build extension binaries
    uses: duckdb/extension-ci-tools/.github/workflows/_extension_distribution.yml@main
    with:
      duckdb_version: main
      extension_name: xxhash
      exclude_archs: ;windows_amd64;windows_arm64;windows_amd64_rtools;wasm_eh;wasm_threads;wasm_mvp;
      enable_go: true
      custom_toolchain_script: true

  duckdb-stable-build:
    name: Build extension binaries
    uses: duckdb/extension-ci-tools/.github/workflows/_extension_distribution.yml@v1.1.0
    with:
      duckdb_version: v1.1.0
      extension_name: xxhash
      exclude_archs: ;windows_amd64;windows_arm64;windows_amd64_rtools;wasm_eh;wasm_threads;wasm_mvp;
      enable_go: true
      custom_toolchain_script: true

  duckdb-stable-deploy:
    name: Deploy extension binaries
    needs: duckdb-stable-build
    uses: ./.github/workflows/_extension_deploy.yml
    secrets: inherit
    with:
      duckdb_version: v1.1.0
      extension_name: xxhash
      exclude_archs: ;windows_amd64;windows_arm64;windows_amd64_rtools;wasm_eh;wasm_threads;wasm_mvp;
      deploy_latest: ${{ startsWith(github.ref, 'refs/tags/v') || github.ref == 'refs/heads/main' }}


  docs:
    runs-on: ubuntu-latest
    needs: duckdb-stable-build
    steps:
      - uses: actions/checkout@v4

      - name: Set up DuckDB
        run: |
          wget https://github.com/duckdb/duckdb/releases/download/v1.1.0/duckdb_cli-linux-amd64.zip
          unzip duckdb_cli-linux-amd64.zip
          chmod +x duckdb

      - uses: actions/download-artifact@v3
        with:
          name: xxhash-v1.1.0-extension-linux_amd64_gcc4
          path: build/downloaded

      - name: Install downloaded extension
        run: |
          ./duckdb -c "SET extension_directory = 'build/extension_dir'; FORCE INSTALL 'build/downloaded/xxhash.duckdb_extension';"
          ./duckdb -unsigned -c "LOAD 'build/downloaded/xxhash.duckdb_extension'; select null::go_defined_type"
