#
# This workflow calls the main distribution pipeline from DuckDB to build, test and (optionally) release the extension
#
name: Main Extension Distribution Pipeline
on:
  push:
  pull_request:
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}-${{ github.head_ref || '' }}-${{ github.base_ref || '' }}-${{ github.ref != 'refs/heads/main' || github.sha }}
  cancel-in-progress: true

jobs:
  duckdb-next-build:
    name: Build extension binaries
    uses: ajzo90/extension-ci-tools/.github/workflows/_extension_distribution.yml@main
    #uses: ./.github/workflows/_extension_distribution.yml
    with:
      duckdb_version: main
      extension_name: quack
      enable_go: true
      exclude_archs: ;windows_amd64;windows_arm64;windows_amd64_rtools;wasm_eh;wasm_threads;wasm_mvp;

#  duckdb-stable-build:
#    name: Build extension binaries
#    uses: ./.github/workflows/_extension_distribution.yml
#    with:
#      duckdb_version: v1.1.0
#      extension_name: quack
#      enable_go: true
#      exclude_archs: ;windows_amd64;windows_arm64;windows_amd64_rtools;wasm_eh;wasm_threads;wasm_mvp;
#
#  duckdb-stable-deploy:
#    name: Deploy extension binaries
#    needs: duckdb-stable-build
#    uses: ./.github/workflows/_extension_deploy.yml
#    secrets: inherit
#    with:
#      duckdb_version: v1.1.0
#      extension_name: quack
#      deploy_latest: ${{ startsWith(github.ref, 'refs/tags/v') || github.ref == 'refs/heads/main' }}
